### ISSUE TITLE
初始化hint的阈值问题

### ISSUE THREAD

**Issue by LeslieRan** [cch123/golang-notes#14]
"在 hint <= 7 时，会调用 makemap_small 来进行初始化，如果 hint > 7，则调用 makemap"，我在调试的时候发现不是而是8。这应该跟编译器有关。

**Comment by cch123** [comment]
这个之前和同事聊完有点新结论，假期我整理上来

**Comment by cch123** [comment]
@LeslieRan ，这里之前确实是写错了
而且之前结论也没写全，在编译阶段还需要有逃逸分析的判断，不一定都会进 makemap 逻辑
