### ISSUE TITLE
channel

### ISSUE THREAD

**Issue by selfeasy** [cch123/golang-notes#28]
func main() {
    ch := make(chan int, 100)
    for elem := range ch { // 主要就是这里的 for range...
        fmt.Println(i)
    }
}
这个地方，在输出通道数据后，会报异常，fatal error: all goroutines are asleep - deadlock!
这个问题要怎么解决呢？

**Comment by cch123** [comment]
把消费放在 goroutine 里，在 main 里用 waitgroup 做同步
建议先读一读一些比较基础的书，https://github.com/gopl-zh/gopl-zh.github.com/pull/90/files
